"""
CodeAlpha Internship - Task 2: Exploratory Data Analysis (EDA)
================================================================
Author: (Senior Data Scientist workflow, generated by Claude)

This script performs a complete EDA workflow on a CSV dataset:
    1. Meaningful Questions
    2. Data Structure Exploration
    3. Trends, Patterns & Anomalies (visualizations)
    4. Hypothesis Testing
    5. Data Quality Report

USAGE
-----
    python eda_task2.py                      # auto-detects a .csv in the current folder
    python eda_task2.py my_dataset.csv        # or pass the path explicitly

The script is written to be dataset-agnostic: it inspects whatever numeric,
categorical, and datetime columns exist and adapts its questions, plots, and
hypothesis tests accordingly. If you know your dataset well, feel free to
edit the CONFIG section below to hardcode column names for sharper,
domain-specific analysis.
"""

import os
import sys
import glob
import warnings

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # headless-safe backend
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

warnings.filterwarnings("ignore")

# ----------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------
CSV_PATH = None          # <-- set to "your_file.csv" to force a specific file, or leave None to auto-detect
PLOTS_DIR = "plots"
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)


# ----------------------------------------------------------------------------
# UTILITIES
# ----------------------------------------------------------------------------
def section(title):
    """Pretty-print a section header to the terminal."""
    print("\n" + "=" * 80)
    print(f" {title}")
    print("=" * 80)


def find_csv():
    """Auto-detect a CSV file in the current folder or nearby locations if CSV_PATH is not set."""
    if CSV_PATH:
        if os.path.isabs(CSV_PATH) or os.path.exists(CSV_PATH):
            return CSV_PATH
        script_dir = os.path.dirname(os.path.abspath(__file__))
        candidate = os.path.join(script_dir, CSV_PATH)
        if os.path.exists(candidate):
            return candidate
        return CSV_PATH

    search_dirs = []
    for base in [os.getcwd(), os.path.dirname(os.path.abspath(__file__))]:
        if base and base not in search_dirs:
            search_dirs.append(base)

    candidates = []
    for base in search_dirs:
        candidates.extend(glob.glob(os.path.join(base, "*.csv")))

    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(script_dir)
    if parent_dir and parent_dir not in search_dirs:
        candidates.extend(glob.glob(os.path.join(parent_dir, "*.csv")))

    seen = set()
    unique_candidates = []
    for path in candidates:
        norm = os.path.abspath(path)
        if norm not in seen:
            seen.add(norm)
            unique_candidates.append(norm)

    if not unique_candidates:
     sys.exit(
            "ERROR: No CSV file found in the current directory or nearby folders. "
            "Place a .csv file here, in the script folder, or set CSV_PATH at the top of this script."
        )
    if len(unique_candidates) > 1:
        print(f"Multiple CSVs found: {unique_candidates}. Using the first one: '{unique_candidates[0]}'")
    return unique_candidates[0]


def load_data(path):
    """Load CSV robustly, trying a couple of common encodings/separators."""
    try:
        df = pd.read_csv(path)
    except UnicodeDecodeError:
        df = pd.read_csv(path, encoding="latin1")
    print(f"Loaded '{path}' -> shape {df.shape}")
    return df


def classify_columns(df):
    """Split columns into numeric, categorical, and datetime-like groups."""
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

    # Try to detect datetime-like columns among object columns (by name or by parse success)
    datetime_cols = df.select_dtypes(include=["datetime64"]).columns.tolist()
    for col in list(categorical_cols):
        if any(k in col.lower() for k in ["date", "time", "year", "month", "day"]):
            try:
                parsed = pd.to_datetime(df[col], errors="coerce")
                if parsed.notna().mean() > 0.8:  # mostly parseable
                    datetime_cols.append(col)
                    categorical_cols.remove(col)
            except Exception:
                pass

    return numeric_cols, categorical_cols, datetime_cols


# ----------------------------------------------------------------------------
# 1. MEANINGFUL QUESTIONS
# ----------------------------------------------------------------------------
def print_meaningful_questions(df, numeric_cols, categorical_cols, datetime_cols):
    section("1. MEANINGFUL ANALYTICAL / BUSINESS QUESTIONS")

    questions = []

    if numeric_cols:
        questions.append(
            f"Q1. What is the central tendency and spread of key numeric metrics "
            f"({', '.join(numeric_cols[:3])}...), and do any of them show extreme outliers "
            f"that could distort downstream analysis or modeling?"
        )
    if len(numeric_cols) >= 2:
        questions.append(
            f"Q2. Which pairs of numeric variables are most strongly correlated, and could any "
            f"of these relationships indicate redundancy (multicollinearity) or a meaningful "
            f"business driver worth investigating further?"
        )
    if categorical_cols:
        questions.append(
            f"Q3. How is the data distributed across key categorical groups "
            f"({', '.join(categorical_cols[:3])}...), and are there class imbalances that "
            f"could bias downstream analysis or models?"
        )
    if categorical_cols and numeric_cols:
        questions.append(
            f"Q4. Do numeric metrics differ significantly across categories of "
            f"'{categorical_cols[0]}'? (e.g., does group membership affect the outcome?)"
        )
    if datetime_cols:
        questions.append(
            f"Q5. Is there a discernible trend or seasonality over time in "
            f"'{datetime_cols[0]}' that could inform forecasting or planning?"
        )
    else:
        questions.append(
            "Q5. Which columns have data quality issues (missing values, inconsistent types, "
            "duplicates) that must be addressed before this dataset is analysis- or model-ready?"
        )

    for q in questions:
        print(f"  - {q}")

    return questions


# ----------------------------------------------------------------------------
# 2. DATA STRUCTURE EXPLORATION
# ----------------------------------------------------------------------------
def explore_structure(df):
    section("2. DATA STRUCTURE EXPLORATION")

    print(f"\nDataset dimensions: {df.shape[0]} rows x {df.shape[1]} columns\n")

    print("--- df.info() ---")
    df.info()

    print("\n--- Missing values per column ---")
    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)
    missing_report = pd.DataFrame({"missing_count": missing, "missing_pct": missing_pct})
    missing_report = missing_report[missing_report["missing_count"] > 0].sort_values(
        "missing_count", ascending=False
    )
    if missing_report.empty:
        print("No missing values detected.")
    else:
        print(missing_report)

    print("\n--- Duplicate rows ---")
    dup_count = df.duplicated().sum()
    print(f"Duplicate rows: {dup_count} ({dup_count / len(df) * 100:.2f}% of dataset)")

    print("\n--- df.describe() (numeric summary statistics) ---")
    print(df.describe().T)

    print("\n--- df.describe(include='object') (categorical summary) ---")
    cat_desc = df.describe(include=["object", "category", "bool"])
    if cat_desc.empty:
        print("No categorical columns detected.")
    else:
        print(cat_desc.T)

    return missing_report, dup_count


# ----------------------------------------------------------------------------
# 3. TRENDS, PATTERNS & ANOMALIES (VISUALIZATIONS)
# ----------------------------------------------------------------------------
def generate_visualizations(df, numeric_cols, categorical_cols):
    section("3. TRENDS, PATTERNS & ANOMALIES (VISUALIZATIONS)")
    os.makedirs(PLOTS_DIR, exist_ok=True)

    # --- Histograms for numeric columns ---
    if numeric_cols:
        n = len(numeric_cols)
        ncols = 3
        nrows = int(np.ceil(n / ncols))
        fig, axes = plt.subplots(nrows, ncols, figsize=(6 * ncols, 4 * nrows))
        axes = np.array(axes).reshape(-1)
        for i, col in enumerate(numeric_cols):
            sns.histplot(df[col].dropna(), kde=True, ax=axes[i], color="steelblue")
            axes[i].set_title(f"Distribution of {col}")
        for j in range(i + 1, len(axes)):
            fig.delaxes(axes[j])
        plt.tight_layout()
        path = os.path.join(PLOTS_DIR, "histograms.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"Saved histograms -> {path}")

    # --- Boxplots for outlier detection ---
    if numeric_cols:
        n = len(numeric_cols)
        ncols = 3
        nrows = int(np.ceil(n / ncols))
        fig, axes = plt.subplots(nrows, ncols, figsize=(6 * ncols, 4 * nrows))
        axes = np.array(axes).reshape(-1)
        for i, col in enumerate(numeric_cols):
            sns.boxplot(x=df[col], ax=axes[i], color="salmon")
            axes[i].set_title(f"Boxplot of {col} (outlier check)")
        for j in range(i + 1, len(axes)):
            fig.delaxes(axes[j])
        plt.tight_layout()
        path = os.path.join(PLOTS_DIR, "boxplots.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"Saved boxplots -> {path}")

    # --- Correlation heatmap ---
    if len(numeric_cols) >= 2:
        plt.figure(figsize=(10, 8))
        corr = df[numeric_cols].corr()
        sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0, square=True)
        plt.title("Correlation Heatmap (Numeric Features)")
        plt.tight_layout()
        path = os.path.join(PLOTS_DIR, "correlation_heatmap.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"Saved correlation heatmap -> {path}")

    # --- Bar charts for categorical columns (top 10 categories) ---
    for col in categorical_cols[:5]:  # cap to avoid excessive plots
        plt.figure(figsize=(10, 6))
        top_vals = df[col].value_counts().head(10)
        sns.barplot(x=top_vals.values, y=top_vals.index.astype(str), color="teal")
        plt.title(f"Top categories in {col}")
        plt.xlabel("Count")
        plt.tight_layout()
        safe_name = "".join(c if c.isalnum() else "_" for c in col)
        path = os.path.join(PLOTS_DIR, f"barchart_{safe_name}.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"Saved bar chart for '{col}' -> {path}")

    # --- Pairplot (sampled) for a quick multi-variable relationship view ---
    if 2 <= len(numeric_cols) <= 6:
        sample_df = df[numeric_cols].dropna()
        if len(sample_df) > 500:
            sample_df = sample_df.sample(500, random_state=42)
        pair = sns.pairplot(sample_df, diag_kind="kde", plot_kws={"alpha": 0.5, "s": 20})
        pair.fig.suptitle("Pairwise Relationships (sampled)", y=1.02)
        path = os.path.join(PLOTS_DIR, "pairplot.png")
        pair.savefig(path, dpi=150)
        plt.close()
        print(f"Saved pairplot -> {path}")

    print("\nInsight: Review histograms for skew, boxplots for outliers beyond the "
          "whiskers, and the heatmap for strongly correlated (|r| > 0.7) feature pairs.")


# ----------------------------------------------------------------------------
# 4. HYPOTHESIS TESTING
# ----------------------------------------------------------------------------
def run_hypothesis_tests(df, numeric_cols, categorical_cols):
    section("4. HYPOTHESIS TESTING")

    results = []

    # --- Hypothesis 1: Correlation test between the two numeric columns
    #     with the strongest absolute correlation ---
    if len(numeric_cols) >= 2:
        corr = df[numeric_cols].corr().abs()
        corr_vals = corr.to_numpy(copy=True)
        np.fill_diagonal(corr_vals, 0)
        corr = pd.DataFrame(corr_vals, index=corr.index, columns=corr.columns)
        max_pair = corr.stack().idxmax()
        col_a, col_b = max_pair

        print(f"\nHypothesis 1: There is a statistically significant linear correlation "
              f"between '{col_a}' and '{col_b}'.")
        print("  H0 (null): No linear correlation exists (r = 0).")
        print("  H1 (alt) : A linear correlation exists (r != 0).")

        paired = df[[col_a, col_b]].dropna()
        r, p_value = stats.pearsonr(paired[col_a], paired[col_b])
        alpha = 0.05
        print(f"  Pearson r = {r:.4f}, p-value = {p_value:.4g}")
        if p_value < alpha:
            conclusion = (f"  Conclusion: p-value < {alpha} -> REJECT H0. There IS a statistically "
                          f"significant correlation (r={r:.2f}) between '{col_a}' and '{col_b}'.")
        else:
            conclusion = (f"  Conclusion: p-value >= {alpha} -> FAIL TO REJECT H0. No statistically "
                          f"significant correlation found between '{col_a}' and '{col_b}'.")
        print(conclusion)
        results.append(("H1: Correlation", col_a, col_b, p_value, conclusion.strip()))
    else:
        print("\nHypothesis 1: Skipped (fewer than 2 numeric columns available).")

    # --- Hypothesis 2: Group comparison - does a numeric variable differ
    #     significantly across a categorical variable's groups? ---
    if numeric_cols and categorical_cols:
        # pick the categorical column with a manageable number of groups (2-10)
        cat_col = None
        for c in categorical_cols:
            n_unique = df[c].nunique(dropna=True)
            if 2 <= n_unique <= 10:
                cat_col = c
                break
        num_col = numeric_cols[0]

        if cat_col:
            print(f"\nHypothesis 2: The mean of '{num_col}' differs significantly across "
                  f"groups of '{cat_col}'.")
            print("  H0 (null): All group means are equal.")
            print("  H1 (alt) : At least one group mean differs.")

            groups = [g.dropna().values for _, g in df.groupby(cat_col)[num_col]]
            groups = [g for g in groups if len(g) > 1]

            if len(groups) >= 2:
                f_stat, p_value = stats.f_oneway(*groups)
                alpha = 0.05
                print(f"  ANOVA F-statistic = {f_stat:.4f}, p-value = {p_value:.4g}")
                if p_value < alpha:
                    conclusion = (f"  Conclusion: p-value < {alpha} -> REJECT H0. Mean '{num_col}' "
                                  f"differs significantly across groups of '{cat_col}'.")
                else:
                    conclusion = (f"  Conclusion: p-value >= {alpha} -> FAIL TO REJECT H0. No significant "
                                  f"difference in mean '{num_col}' across groups of '{cat_col}'.")
                print(conclusion)
                results.append(("H2: Group comparison (ANOVA)", num_col, cat_col, p_value, conclusion.strip()))
            else:
                print("  Skipped: not enough groups with sufficient data for ANOVA.")
        else:
            print("\nHypothesis 2: Skipped (no categorical column with 2-10 groups found).")
    else:
        print("\nHypothesis 2: Skipped (need at least one numeric and one categorical column).")

    return results


# ----------------------------------------------------------------------------
# 5. DATA QUALITY REPORT
# ----------------------------------------------------------------------------
def data_quality_report(df, numeric_cols, missing_report, dup_count):
    section("5. DATA QUALITY REPORT")

    issues = []
    recommendations = []

    # Missing values
    if not missing_report.empty:
        for col, row in missing_report.iterrows():
            issues.append(f"Column '{col}' has {int(row['missing_count'])} missing values "
                          f"({row['missing_pct']}%).")
        recommendations.append(
            "Impute missing numeric values with median/mean (or a model-based imputer), and "
            "missing categorical values with mode or an explicit 'Unknown' category. "
            "Consider dropping columns with >50% missing data."
        )
    else:
        issues.append("No missing values detected.")

    # Duplicate rows
    if dup_count > 0:
        issues.append(f"{dup_count} duplicate rows detected.")
        recommendations.append("Drop duplicate rows using df.drop_duplicates() unless duplicates "
                                "are legitimate repeated observations.")
    else:
        issues.append("No duplicate rows detected.")

    # Skewness
    skewed_cols = []
    for col in numeric_cols:
        skew_val = df[col].skew()
        if abs(skew_val) > 1:
            skewed_cols.append((col, round(skew_val, 2)))
    if skewed_cols:
        for col, sk in skewed_cols:
            issues.append(f"Column '{col}' is highly skewed (skewness = {sk}).")
        recommendations.append(
            "Apply a log, sqrt, or Box-Cox transform to highly skewed numeric columns "
            "to reduce skew before modeling, especially for linear models."
        )
    else:
        issues.append("No strongly skewed numeric columns detected (|skew| <= 1).")

    # Outliers via IQR method
    outlier_cols = []
    for col in numeric_cols:
        q1, q3 = df[col].quantile([0.25, 0.75])
        iqr = q3 - q1
        lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()
        if n_outliers > 0:
            outlier_cols.append((col, n_outliers))
    if outlier_cols:
        for col, n in outlier_cols:
            issues.append(f"Column '{col}' has {n} potential outliers (IQR method).")
        recommendations.append(
            "Investigate outliers individually: cap/winsorize, transform, or remove them "
            "depending on whether they represent data errors or genuine extreme values."
        )
    else:
        issues.append("No significant outliers detected via IQR method.")

    # Constant / near-constant columns
    for col in df.columns:
        if df[col].nunique(dropna=True) <= 1:
            issues.append(f"Column '{col}' has only 1 unique value and carries no analytical signal.")
            recommendations.append(f"Consider dropping the constant column '{col}'.")

    # Data type mismatches (numbers stored as text, etc.)
    for col in df.select_dtypes(include="object").columns:
        sample = df[col].dropna().astype(str).head(50)
        numeric_like = sample.str.match(r"^-?\d+\.?\d*$").mean() if len(sample) else 0
        if numeric_like > 0.9:
            issues.append(f"Column '{col}' looks numeric but is stored as text/object dtype.")
            recommendations.append(f"Convert '{col}' to a numeric dtype with pd.to_numeric().")

    print("\n--- Detected Issues ---")
    for i, issue in enumerate(issues, 1):
        print(f"  {i}. {issue}")

    print("\n--- Recommendations for Preprocessing ---")
    if recommendations:
        for i, rec in enumerate(dict.fromkeys(recommendations), 1):  # dedupe, preserve order
            print(f"  {i}. {rec}")
    else:
        print("  Dataset appears clean; minimal preprocessing required.")


# ----------------------------------------------------------------------------
# MAIN
# ----------------------------------------------------------------------------
def main():
    csv_path = sys.argv[1] if len(sys.argv) > 1 else find_csv()
    df = load_data(csv_path)

    numeric_cols, categorical_cols, datetime_cols = classify_columns(df)

    print_meaningful_questions(df, numeric_cols, categorical_cols, datetime_cols)
    missing_report, dup_count = explore_structure(df)
    generate_visualizations(df, numeric_cols, categorical_cols)
    run_hypothesis_tests(df, numeric_cols, categorical_cols)
    data_quality_report(df, numeric_cols, missing_report, dup_count)

    section("EDA COMPLETE")
    print(f"All plots saved to the '{PLOTS_DIR}/' directory.")


if __name__ == "__main__":
    main()